name: Deploy

on:
  workflow_run:
    workflows: ["CI"]              # Название должно совпадать с name: CI в ci.yml
    types:
      - completed
    branches:
      - main           # деплоим на каждый push в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Convert owner to lowercase
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${OWNER_LOWER}/marketplace-service" >> $GITHUB_ENV

             
      - name: Deploy to server            # зайти на сервер по SSH и перезапустить контейнер
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}      # host/user/ключ — всё из секретов, в коде их нет
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE
          script: |                              # команды ниже выполняются НА сервере:
            # залогиниться в реестр, чтобы стянуть приватный образ
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull $IMAGE:latest                          # стянуть свежий образ
            docker rm -f marketplace-satisfaction 2>/dev/null || true    # снести старый контейнер, если был
            docker run -d \
              --name marketplace-satisfaction \
              --restart unless-stopped \
              -p 127.0.0.1:8000:8000 \
              $IMAGE:latest
            docker logout ghcr.io